# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r test_requirements.txt
<<<<<<< HEAD
# Command to run tests, e.g. python setup.py test
script: tox

=======
>>>>>>> parent of 0cdde14... Travis
# Command to run tests, e.g. python setup.py test
before_script:
  - "pip install ."

script: pytest tests/test_*.py